INSERT INTO "OccupationalRisk" ("id", "cboCode", "functionName", "riskGrade", "requiresInPerson", "requiredExams", "periodicFrequencyMonths")
VALUES
(gen_random_uuid(), '2141-05', 'Médico do Trabalho', 'baixo', false, ARRAY['audiometria', 'espirometria', 'acuidade_visual'], 12),
(gen_random_uuid(), '2141-10', 'Médico Ocupacional', 'baixo', false, ARRAY['audiometria', 'espirometria', 'acuidade_visual'], 12),
(gen_random_uuid(), '3221-05', 'Técnico em Segurança do Trabalho', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '3221-10', 'Técnico de Segurança do Trabalho', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7111-05', 'Operador de Máquinas Fixas', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'eletroencefalograma'], 6),
(gen_random_uuid(), '7112-10', 'Operador de Máquinas Móveis', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 6),
(gen_random_uuid(), '7211-10', 'Moldador de Fundição', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'radiografia_torax'], 6),
(gen_random_uuid(), '7232-10', 'Soldador', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'radiografia_torax', 'eletrocardiograma'], 6),
(gen_random_uuid(), '7241-05', 'Mecânico de Manutenção', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7242-10', 'Mecânico de Máquinas Industriais', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7251-10', 'Eletricista de Manutenção', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'eletroencefalograma'], 12),
(gen_random_uuid(), '7842-05', 'Operador de Processos Químicos', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'radiografia_torax', 'exames_laboratoriais'], 6),
(gen_random_uuid(), '8111-10', 'Operador de Caldeira', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'radiografia_torax'], 6),
(gen_random_uuid(), '8131-05', 'Operador de Moagem', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'radiografia_torax'], 6),
(gen_random_uuid(), '8411-10', 'Motorista de Caminhão', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'psicossocial'], 12),
(gen_random_uuid(), '8412-05', 'Motorista de Ônibus', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'psicossocial'], 12),
(gen_random_uuid(), '9111-05', 'Operador de Produção', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual'], 12),
(gen_random_uuid(), '9112-10', 'Ajudante de Produção', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual'], 12),
(gen_random_uuid(), '9191-05', 'Trabalhador em Exposição a Ruído', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 6),
(gen_random_uuid(), '9192-10', 'Trabalhador em Exposição a Poeira', 'alto', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'radiografia_torax', 'espirometria'], 6),
(gen_random_uuid(), '9511-05', 'Vigia', 'baixo', false, ARRAY['audiometria', 'acuidade_visual'], 24),
(gen_random_uuid(), '5121-05', 'Cozinheiro Industrial', 'baixo', false, ARRAY['audiometria', 'acuidade_visual', 'exames_laboratoriais'], 12),
(gen_random_uuid(), '5143-10', 'Atendente de Enfermagem', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'exames_laboratoriais'], 12),
(gen_random_uuid(), '4110-05', 'Escriturário', 'baixo', false, ARRAY['acuidade_visual'], 24),
(gen_random_uuid(), '4141-05', 'Almoxarife', 'baixo', false, ARRAY['audiometria', 'acuidade_visual'], 24),
(gen_random_uuid(), '7151-10', 'Carpinteiro', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7152-05', 'Armador de Ferragens', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7153-10', 'Pedreiro', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma', 'radiografia_torax'], 12),
(gen_random_uuid(), '7154-05', 'Azulejista', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12),
(gen_random_uuid(), '7155-10', 'Gesseiro', 'medio', true, ARRAY['audiometria', 'espirometria', 'acuidade_visual', 'eletrocardiograma'], 12)
ON CONFLICT ("cboCode") DO UPDATE SET
  "functionName" = EXCLUDED."functionName",
  "riskGrade" = EXCLUDED."riskGrade",
  "requiresInPerson" = EXCLUDED."requiresInPerson",
  "requiredExams" = EXCLUDED."requiredExams",
  "periodicFrequencyMonths" = EXCLUDED."periodicFrequencyMonths";
