import { PrismaService } from '../prisma.service';
import { CreateCompanyDto } from './dto/create-company.dto';
import { UpdateCompanyDto } from './dto/update-company.dto';
import { CreateInviteDto } from './dto/create-invite.dto';
import { CompanyGateway } from './company.gateway';
import { MailService } from '../mail/mail.service';
import { SupabaseStorageService } from '../upload/supabase-storage.service';
export declare class CompanyService {
    private prisma;
    private companyGateway;
    private mailService;
    private storage;
    constructor(prisma: PrismaService, companyGateway: CompanyGateway, mailService: MailService, storage: SupabaseStorageService);
    createCompany(dto: CreateCompanyDto): Promise<{
        company: {
            id: string;
            cnpj: string;
            razaoSocial: string;
            nomeFantasia: string | null;
            name: string | null;
            planType: string | null;
            address: string | null;
            cep: string | null;
            city: string | null;
            state: string | null;
            phone: string | null;
            contactEmail: string | null;
            lat: number | null;
            lng: number | null;
            status: import(".prisma/client").$Enums.CompanyStatus;
            clinicId: string | null;
            pcmsoDocumentUrl: string | null;
            ppraDocumentUrl: string | null;
            pcmsoValidUntil: Date | null;
            ppraValidUntil: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        user: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            email: string;
            role: import(".prisma/client").$Enums.Role;
        };
    }>;
    getCompany(companyId: string): Promise<({
        clinic: {
            id: string;
            cnpj: string;
            name: string;
            address: string | null;
            city: string | null;
            state: string | null;
            phone: string | null;
            contactEmail: string | null;
            lat: number | null;
            lng: number | null;
            createdAt: Date;
            updatedAt: Date;
            userId: string | null;
            credentialSource: string | null;
            isActive: boolean;
            isFranchise: boolean;
            isMatriz: boolean;
            parentClinicId: string | null;
        } | null;
        admins: {
            id: string;
            createdAt: Date;
            userId: string;
            companyId: string;
        }[];
    } & {
        id: string;
        cnpj: string;
        razaoSocial: string;
        nomeFantasia: string | null;
        name: string | null;
        planType: string | null;
        address: string | null;
        cep: string | null;
        city: string | null;
        state: string | null;
        phone: string | null;
        contactEmail: string | null;
        lat: number | null;
        lng: number | null;
        status: import(".prisma/client").$Enums.CompanyStatus;
        clinicId: string | null;
        pcmsoDocumentUrl: string | null;
        ppraDocumentUrl: string | null;
        pcmsoValidUntil: Date | null;
        ppraValidUntil: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }) | null>;
    listCompanies(): Promise<({
        clinic: {
            id: string;
            cnpj: string;
            name: string;
            address: string | null;
            city: string | null;
            state: string | null;
            phone: string | null;
            contactEmail: string | null;
            lat: number | null;
            lng: number | null;
            createdAt: Date;
            updatedAt: Date;
            userId: string | null;
            credentialSource: string | null;
            isActive: boolean;
            isFranchise: boolean;
            isMatriz: boolean;
            parentClinicId: string | null;
        } | null;
    } & {
        id: string;
        cnpj: string;
        razaoSocial: string;
        nomeFantasia: string | null;
        name: string | null;
        planType: string | null;
        address: string | null;
        cep: string | null;
        city: string | null;
        state: string | null;
        phone: string | null;
        contactEmail: string | null;
        lat: number | null;
        lng: number | null;
        status: import(".prisma/client").$Enums.CompanyStatus;
        clinicId: string | null;
        pcmsoDocumentUrl: string | null;
        ppraDocumentUrl: string | null;
        pcmsoValidUntil: Date | null;
        ppraValidUntil: Date | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    updateCompany(companyId: string, dto: UpdateCompanyDto): Promise<{
        id: string;
        cnpj: string;
        razaoSocial: string;
        nomeFantasia: string | null;
        name: string | null;
        planType: string | null;
        address: string | null;
        cep: string | null;
        city: string | null;
        state: string | null;
        phone: string | null;
        contactEmail: string | null;
        lat: number | null;
        lng: number | null;
        status: import(".prisma/client").$Enums.CompanyStatus;
        clinicId: string | null;
        pcmsoDocumentUrl: string | null;
        ppraDocumentUrl: string | null;
        pcmsoValidUntil: Date | null;
        ppraValidUntil: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateCompanyStatus(companyId: string, status: string): Promise<{
        id: string;
        cnpj: string;
        razaoSocial: string;
        nomeFantasia: string | null;
        name: string | null;
        planType: string | null;
        address: string | null;
        cep: string | null;
        city: string | null;
        state: string | null;
        phone: string | null;
        contactEmail: string | null;
        lat: number | null;
        lng: number | null;
        status: import(".prisma/client").$Enums.CompanyStatus;
        clinicId: string | null;
        pcmsoDocumentUrl: string | null;
        ppraDocumentUrl: string | null;
        pcmsoValidUntil: Date | null;
        ppraValidUntil: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    createInvite(companyId: string, dto: CreateInviteDto): Promise<{
        company: {
            id: string;
            cnpj: string;
            razaoSocial: string;
            nomeFantasia: string | null;
            name: string | null;
            planType: string | null;
            address: string | null;
            cep: string | null;
            city: string | null;
            state: string | null;
            phone: string | null;
            contactEmail: string | null;
            lat: number | null;
            lng: number | null;
            status: import(".prisma/client").$Enums.CompanyStatus;
            clinicId: string | null;
            pcmsoDocumentUrl: string | null;
            ppraDocumentUrl: string | null;
            pcmsoValidUntil: Date | null;
            ppraValidUntil: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        status: import(".prisma/client").$Enums.InviteStatus;
        clinicId: string | null;
        createdAt: Date;
        examType: string;
        token: string;
        paymentId: string | null;
        companyId: string;
        expectedCpf: string | null;
        expectedEmail: string | null;
        roleFunction: string;
        roleFunctionCboCode: string | null;
        expiresAt: Date;
        sentAt: Date;
        openedAt: Date | null;
        collaboratorName: string | null;
        expectedBirthDate: Date | null;
    }>;
    listInvites(companyId: string): Promise<({
        examRequest: ({
            results: {
                id: string;
                requestId: string;
                source: string;
                typeId: string;
                valueJson: string;
                attachmentUrl: string | null;
                collectedById: string;
                collectedAt: Date;
            }[];
        } & {
            id: string;
            status: string;
            clinicId: string | null;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            inviteId: string | null;
            source: string;
            examPurpose: string;
            paymentId: string | null;
        }) | null;
        timelineEvents: {
            id: string;
            inviteId: string | null;
            eventType: import(".prisma/client").$Enums.TimelineEventType;
            occurredAt: Date;
            metadata: string | null;
            examRequestId: string | null;
        }[];
    } & {
        id: string;
        status: import(".prisma/client").$Enums.InviteStatus;
        clinicId: string | null;
        createdAt: Date;
        examType: string;
        token: string;
        paymentId: string | null;
        companyId: string;
        expectedCpf: string | null;
        expectedEmail: string | null;
        roleFunction: string;
        roleFunctionCboCode: string | null;
        expiresAt: Date;
        sentAt: Date;
        openedAt: Date | null;
        collaboratorName: string | null;
        expectedBirthDate: Date | null;
    })[]>;
    listActiveAsos(companyId: string): Promise<{
        id: string;
        requestId: string;
        collaborator: {
            id: string;
            name: string;
            cpf: string;
            functionCboCode: string | null;
        };
        examType: string;
        examPurpose: string;
        issuedAt: string;
        validUntil: string;
        daysUntilExpiration: number;
        decision: string;
        restrictionNotes: string | null;
        pdfUrl: string | null;
        doctor: {
            id: string;
            name: string;
            crm: string;
        };
    }[]>;
    getAsoPdf(companyId: string, asoId: string): Promise<{
        buffer: Buffer<ArrayBufferLike>;
        fileName: string;
    }>;
    cancelInvite(inviteId: string): Promise<{
        id: string;
        status: import(".prisma/client").$Enums.InviteStatus;
        clinicId: string | null;
        createdAt: Date;
        examType: string;
        token: string;
        paymentId: string | null;
        companyId: string;
        expectedCpf: string | null;
        expectedEmail: string | null;
        roleFunction: string;
        roleFunctionCboCode: string | null;
        expiresAt: Date;
        sentAt: Date;
        openedAt: Date | null;
        collaboratorName: string | null;
        expectedBirthDate: Date | null;
    }>;
    findInviteByCpf(cpf: string, user: {
        role: string;
        profileId?: string | null;
    }): Promise<({
        company: {
            id: string;
            cnpj: string;
            razaoSocial: string;
            nomeFantasia: string | null;
            name: string | null;
            planType: string | null;
            address: string | null;
            cep: string | null;
            city: string | null;
            state: string | null;
            phone: string | null;
            contactEmail: string | null;
            lat: number | null;
            lng: number | null;
            status: import(".prisma/client").$Enums.CompanyStatus;
            clinicId: string | null;
            pcmsoDocumentUrl: string | null;
            ppraDocumentUrl: string | null;
            pcmsoValidUntil: Date | null;
            ppraValidUntil: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        status: import(".prisma/client").$Enums.InviteStatus;
        clinicId: string | null;
        createdAt: Date;
        examType: string;
        token: string;
        paymentId: string | null;
        companyId: string;
        expectedCpf: string | null;
        expectedEmail: string | null;
        roleFunction: string;
        roleFunctionCboCode: string | null;
        expiresAt: Date;
        sentAt: Date;
        openedAt: Date | null;
        collaboratorName: string | null;
        expectedBirthDate: Date | null;
    }) | null>;
    getInviteTimeline(inviteId: string): Promise<{
        invite: {
            examRequest: ({
                asoDocuments: {
                    id: string;
                    requestId: string;
                    doctorId: string;
                    decision: string;
                    restrictionNotes: string | null;
                    pdfUrl: string | null;
                    signatureProviderId: string | null;
                    signedAt: Date | null;
                    validUntil: Date | null;
                }[];
            } & {
                id: string;
                status: string;
                clinicId: string | null;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                inviteId: string | null;
                source: string;
                examPurpose: string;
                paymentId: string | null;
            }) | null;
            timelineEvents: {
                id: string;
                inviteId: string | null;
                eventType: import(".prisma/client").$Enums.TimelineEventType;
                occurredAt: Date;
                metadata: string | null;
                examRequestId: string | null;
            }[];
        } & {
            id: string;
            status: import(".prisma/client").$Enums.InviteStatus;
            clinicId: string | null;
            createdAt: Date;
            examType: string;
            token: string;
            paymentId: string | null;
            companyId: string;
            expectedCpf: string | null;
            expectedEmail: string | null;
            roleFunction: string;
            roleFunctionCboCode: string | null;
            expiresAt: Date;
            sentAt: Date;
            openedAt: Date | null;
            collaboratorName: string | null;
            expectedBirthDate: Date | null;
        };
        timeline: {
            id: string;
            inviteId: string | null;
            eventType: import(".prisma/client").$Enums.TimelineEventType;
            occurredAt: Date;
            metadata: string | null;
            examRequestId: string | null;
        }[];
        finalResult: string | null;
    }>;
    recordTimelineEvent(data: {
        inviteId?: string;
        examRequestId?: string;
        eventType: string;
    }): Promise<{
        id: string;
        inviteId: string | null;
        eventType: import(".prisma/client").$Enums.TimelineEventType;
        occurredAt: Date;
        metadata: string | null;
        examRequestId: string | null;
    }>;
    getDashboardStats(companyId: string): Promise<{
        total: number;
        sent: number;
        opened: number;
        inProgress: number;
        completed: number;
        expired: number;
    }>;
    getStatusCheck(companyId: string): Promise<{
        hasRazaoSocial: boolean;
        hasPcmso: boolean;
        hasPpra: boolean;
        pcmsoValid: boolean;
        ppraValid: boolean;
        hasClinicAssigned: boolean;
        clinic: {
            id: string;
            name: string;
            address: string | null;
            city: string | null;
            state: string | null;
        } | null;
        status: import(".prisma/client").$Enums.CompanyStatus;
        isComplete: boolean;
    }>;
    listInvitesForAllCompanies(): Promise<({
        examRequest: ({
            results: {
                id: string;
                requestId: string;
                source: string;
                typeId: string;
                valueJson: string;
                attachmentUrl: string | null;
                collectedById: string;
                collectedAt: Date;
            }[];
        } & {
            id: string;
            status: string;
            clinicId: string | null;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            inviteId: string | null;
            source: string;
            examPurpose: string;
            paymentId: string | null;
        }) | null;
        timelineEvents: {
            id: string;
            inviteId: string | null;
            eventType: import(".prisma/client").$Enums.TimelineEventType;
            occurredAt: Date;
            metadata: string | null;
            examRequestId: string | null;
        }[];
    } & {
        id: string;
        status: import(".prisma/client").$Enums.InviteStatus;
        clinicId: string | null;
        createdAt: Date;
        examType: string;
        token: string;
        paymentId: string | null;
        companyId: string;
        expectedCpf: string | null;
        expectedEmail: string | null;
        roleFunction: string;
        roleFunctionCboCode: string | null;
        expiresAt: Date;
        sentAt: Date;
        openedAt: Date | null;
        collaboratorName: string | null;
        expectedBirthDate: Date | null;
    })[]>;
    gerarRelatorio(companyId: string, de?: string, ate?: string): Promise<string[]>;
    findBestClinicForCompany(companyId: string, ignoreCurrentAssignment?: boolean): Promise<{
        id: string;
        name: string;
        city: string | null;
        state: string | null;
        isMatriz: boolean;
    } | null>;
    private distanceKm;
}
